spring:
  profiles:
    active: window-dev
---
logging:
  level:
    yongs:
      temp: DEBUG
    com:
      netflix:
        eureka: OFF
        discovery: OFF  
      
spring:
  profiles: window-dev
  application:
    name: yongs-batch
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/flex
